export const DropData = [
                    {
                      cname:"dropitems",
                      path:"/wolof", 
                      name:"Wolof" 
                    },
                    {
                      cname:"dropitems",
                      path:"/yoruba", 
                      name:"Yoruba" 
                    },
                    {
                      cname:"dropitems",
                      path:"/ashanti", 
                      name:"Ashanti" 
                    },
                    {
                      cname:"dropitems",
                      path:"/geechie", 
                      name:"Geechie" 
                    },
                    {
                      cname:"dropitems",
                      path:"krio", 
                      name:"Krio" 
                    }
]